#!/usr/bin/env python

import sys; sys.dont_write_bytecode = True
import os
os.environ["PIDJ_SETTINGS"] = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.py")

import pidj
import sys

port = 5000
if len(sys.argv) >= 2:
   port = int(sys.argv[1])

pidj.run(port)
